// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmhggdcrmdkyaymvcmmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaGdnZGNybWRreWF5bXZjbW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NTA1MTMsImV4cCI6MjA3MDUyNjUxM30.VEXyyBa8Pn_YDaOcw6zL5Lq7E5qWgHqO7m4nZVQyvf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});